name: madcamp_week2
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.4
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.9
  intl: ^0.19.0
  json_annotation: ^4.8.1
  kakao_flutter_sdk_user: ^1.8.0
  retrofit: ^4.0.3
  shimmer: ^3.0.0
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  riverpod_lint: ^2.3.7
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
